export const GET_TWEETS = "GET_TWEETS";
export const GET_TWEETS_SUCCESS = "GET_TWEETS_SUCCESS";
export const GET_TWEETS_FAIL = "GET_TWEETS_FAIL";
export const LIKE_TWEET = "LIKE_TWEET";
export const LIKE_TWEET_SUCCESS = "LIKE_TWEET_SUCCESS";
export const LIKE_TWEET_FAIL = "LIKE_TWEET_FAIL";
